# Generated by Django 2.1.4 on 2019-12-05 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0004_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='categories',
            field=models.ManyToManyField(to='apps.Category'),
        ),
    ]
