# Generated by Django 2.1.4 on 2019-12-05 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0005_app_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='head_img',
            field=models.FileField(blank=True, null=True, upload_to='static/images/heads'),
        ),
    ]
