# Generated by Django 2.1.4 on 2019-12-05 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0008_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='rate',
            name='review',
            field=models.TextField(null=True),
        ),
    ]
