# Generated by Django 2.1.4 on 2019-12-05 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0009_rate_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='rate',
            name='app',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apps.App'),
        ),
    ]
