# Generated by Django 2.1.4 on 2019-12-05 18:40

from django.db import migrations, models
import django.db.models.deletion
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0010_rate_app'),
    ]

    operations = [
        migrations.CreateModel(
            name='Update',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('features', django_mysql.models.ListTextField(models.CharField(max_length=1000), blank=True, null=True, size=5000)),
                ('date_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('app', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apps.App')),
            ],
        ),
    ]
